version: "3.3"

services:
  # Application
  dp-app:
    image: dp-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    command: [ "php-fpm" ]
    container_name: dp-app
    restart: unless-stopped
    tty: true
    volumes:
      - dp-data:/www:nocopy
      - ~/.ssh:/root/.ssh:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
    environment:
      TIMEZONE: "UTC"
      COMPOSER_MEMORY_LIMIT: "-1"
    expose:
      - 9000
    networks:
      - dp-network

  # Nginx Webserver
  dp-webserver:
    image: nginx:1.17-alpine
    container_name: dp-webserver
    restart: unless-stopped
    tty: true
    expose:
      - 80
      - 443
    volumes:
      - dp-data:/www:nocopy
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/:delegated
    networks:
      - dp-network

  # NPM watch
  dp-npm:
    image: amd64/node:12.14.1-alpine
    container_name: dp-npm
    working_dir: /www
    command: sh -c "npm ci && npm run watch-poll"
    volumes:
      - dp-data:/www:nocopy
    networks:
      - dp-network

  # MySQL
  dp-db:
    image: percona:5.7.19
    container_name: dp-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: doctorproffi
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - dbdata-logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
      - ./docker/mysql/inten.sql:/docker-entrypoint-initdb.d/dump.sql:delegated
    networks:
      - dp-network

  # Redis Service
  dp-redis:
    image: redis:5.0.7-alpine
    container_name: dp-redis
    restart: unless-stopped
    volumes:
      - cachedata:/data
    networks:
      - dp-network

  # Supervisord
  dp-supervisord:
    image: dp-app
    container_name: dp-supervisord
    restart: unless-stopped
    tty: true
    user: root
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf" ]
    depends_on:
      - dp-db
      - dp-redis
    expose:
      - 9123
    volumes:
      - dp-data:/www:nocopy
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf:delegated
      - ./docker/supervisord/conf.d:/etc/supervisor/conf.d:delegated
      - ./docker/php/php.ini:/etc/php.ini:delegated
    networks:
      - dp-network

# Docker Networks
networks:
  dp-network:
    driver: bridge

# Volumes
volumes:
  dp-data:
    external: true
  dbdata:
    driver: local
  dbdata-logs:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cachedata:
    driver: local
