version: "3.3"

services:
  # Application
  dp-app:
    image: dp-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    command: [ "php-fpm" ]
    container_name: dp-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/www:delegated
      - ~/.ssh:/root/.ssh:delegated
      - ~/.composer:/var/www/.composer:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
    environment:
      TIMEZONE: "UTC"
      XDEBUG_CONFIG: "remote_enable=1 remote_port=9001 remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=Docker"
      COMPOSER_MEMORY_LIMIT: "-1"
    expose:
      - 9000
    networks:
      - dp-network

  # Nginx Webserver
  dp-webserver:
    image: nginx:1.19.3-alpine
    container_name: dp-webserver
    restart: unless-stopped
    tty: true
    expose:
      - 80
      - 443
    volumes:
      - ./:/www:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/:delegated
    networks:
      - dp-network

  # NPM watch
  dp-npm:
    image: node:lts-buster
    container_name: dp-npm
    working_dir: /www
    command: sh -c "npm ci && npm run watch"
    volumes:
      - ./:/www:delegated
    networks:
      - dp-network

  # MySQL
  dp-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: dp-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: doctorproffi
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - dbdata-logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
      - ./docker/mysql/dp.sql:/docker-entrypoint-initdb.d/dump.sql:delegated
    networks:
      - dp-network

  # Redis Service
  dp-redis:
    image: redis:5.0.7-alpine
    container_name: dp-redis
    restart: unless-stopped
    volumes:
      - cachedata:/data
    networks:
      - dp-network

  # Supervisord
  dp-supervisord:
    image: dp-app
    container_name: dp-supervisord
    restart: unless-stopped
    tty: true
    user: root
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf" ]
    depends_on:
      - dp-db
      - dp-redis
    expose:
      - 9123
    volumes:
      - ./:/www:delegated
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf:delegated
      - ./docker/supervisord/conf.d:/etc/supervisor/conf.d:delegated
      - ./docker/php/php.ini:/etc/php.ini:delegated
    networks:
      - dp-network

# Docker Networks
networks:
  dp-network:
    driver: bridge

# Volumes
volumes:
  dp-data:
    external: true
  dbdata:
    driver: local
  dbdata-logs:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cachedata:
    driver: local
