FROM composer:latest

ENV PHPREDIS_VERSION 5.1.1

RUN mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    && docker-php-ext-install \
        mysqli \
        pdo \
        pdo_mysql \
        redis
